<?php

/**
 * PluginSongFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSongFileTable extends Doctrine_Table
{
  const PUBLIC_FLAG_OPEN    = 4;
  const PUBLIC_FLAG_SNS     = 1;
  const PUBLIC_FLAG_FRIEND  = 2;
  const PUBLIC_FLAG_PRIVATE = 3;

  protected static $publicFlags = array(
    self::PUBLIC_FLAG_OPEN    => 'All Users on the Web',
    self::PUBLIC_FLAG_SNS     => 'All Members',
    self::PUBLIC_FLAG_FRIEND  => '%my_friend%',
    self::PUBLIC_FLAG_PRIVATE => 'Private',
  );

  /**
   * Returns an instance of this class.
   *
   * @return object PluginSongFileTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginSongFile');
  }

  public function getPublicFlags()
  {
    if (!sfConfig::get('app_op_diary_plugin_is_open', true))
    {
      unset(self::$publicFlags[self::PUBLIC_FLAG_OPEN]);
    }

    $publicFlags = array();

    $i18n = sfContext::getInstance()->getI18N();
    $termMyFriend = Doctrine::getTable('SnsTerm')->get('my_friend');

    foreach (self::$publicFlags as $key => $publicFlag)
    {
      $terms = array('%my_friend%' => $termMyFriend->pluralize()->titleize());
      $publicFlags[$key] = $i18n->__($publicFlag, $terms, 'publicFlags');
    }

    return $publicFlags;
  }

  public function getMyList($limit = 5)
  {
    return $this->getMemberList(null, $limit);
  }

  public function getMemberList($memberId = null, $limit = 5)
  {
    $memberId = $memberId ? $memberId : sfContext::getInstance()->getUser()->getMemberId();

    return $this->createOrderByQuery()
      ->where('member_id = ?', sfContext::getInstance()->getUser()->getMemberId())
      ->limit($limit)
      ->execute();
  }

  protected function createOrderByQuery()
  {
    return $this->createQuery()->orderBy('created_at DESC');
  }
}
