<?php

/**
 * PluginSongFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSongFileTable extends Doctrine_Table
{
  const PUBLIC_FLAG_OPEN    = 4;
  const PUBLIC_FLAG_SNS     = 3;
  const PUBLIC_FLAG_FRIEND  = 2;
  const PUBLIC_FLAG_PRIVATE = 1;

  protected static $publicFlags = array(
    self::PUBLIC_FLAG_OPEN    => 'All Users on the Web',
    self::PUBLIC_FLAG_SNS     => 'All Members',
    self::PUBLIC_FLAG_FRIEND  => '%my_friend%',
    self::PUBLIC_FLAG_PRIVATE => 'Private',
  );

  /**
   * Returns an instance of this class.
   *
   * @return object PluginSongFileTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginSongFile');
  }

  public function getPublicFlags()
  {
    $publicFlags = array();

    $i18n = sfContext::getInstance()->getI18N();
    $termMyFriend = Doctrine::getTable('SnsTerm')->get('my_friend');

    foreach (self::$publicFlags as $key => $publicFlag)
    {
      $terms = array('%my_friend%' => $termMyFriend->pluralize()->titleize());
      $publicFlags[$key] = $i18n->__($publicFlag, $terms, 'publicFlags');
    }

    return $publicFlags;
  }

  public function getMemberList($memberId = null, $limit = 20)
  {
    $memberId = $memberId ? $memberId : sfContext::getInstance()->getUser()->getMemberId();

    return $this->addPublicFlagQuery($this->createOrderByQuery(), $memberId)
      ->andWhere('member_id = ?', sfContext::getInstance()->getUser()->getMemberId())
      ->limit($limit)
      ->execute();
  }

  public function addPublicFlagQuery(Doctrine_Query $q, $memberId)
  {
    $myId = sfContext::getInstance()->getUser()->getMemberId();
    if ($memberId == $myId)
    {
      return $q;
    }
    if (null == $memberId)
    {
      return $q->andWhere('public_flag = ?', self::PUBLIC_FLAG_OPEN);
    }

    $relation = Doctrine::getTable('MemberRelationship')->retrieveByFromAndTo($memberId, $myId);
    if ($relation && $relation->isFriend())
    {
      return $q->andWhere('public_flag >= ?', self::PUBLIC_FLAG_FRIEND);
    }

    return $q->andWhere('public_flag >= ?', self::PUBLIC_FLAG_SNS);
  }

  protected function createOrderByQuery()
  {
    return $this->createQuery()->where(1)->orderBy('created_at DESC');
  }
}
