<?php

/**
 * PluginSongVoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSongVoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSongVoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSongVote');
    }
}