options:
  charset: utf8

SongFile:
  actAs: [Timestampable]
  columns:
    id: { type: integer(4), primary: true, autoincrement: true }
    member_id: { type: integer(4), notnull: true }
    title: { type: string, notnull: true }
    public_flag: { type: integer(1), notnull: true, default: 3 }
    file_id: { type: integer(4), notnull: true }
    is_main: { type: boolean, notnull: true, default: false }
  relations:
    File:
      foreignAlias: SongFiles
      onDelete: cascade
    Member:
      foreignAlias: SongFiles
      onDelete: cascade
  indexes:
    member_id:
      fields: [member_id]
    created_at:
      fields: [created_at]

SongVote:
  actAs: [Timestampable]
  columns:
    id: { type: integer(4), primary: true, autoincrement: true }
    song_file_id: { type: integer(4), notnull: true }
    member_id: { type: integer(4), notnull: true }
    point: { type: integer(2), notnull: true }
    comment: { type: string, notnull: false }
  relations:
    SongFile:
      foreignAlias: SongVotes
      onDelete: cascade
    Member:
      foreignAlias: DiaryComments
      onDelete: cascade
  indexes:
    member_id:
      fields: [member_id]
    song_file_id:
      fields: [song_file_id]
    created_at:
      fields: [created_at]
